### ISSUE TITLE
Spelunky Classic code analysis

### ISSUE THREAD

**Issue by RetroEdit** [dbeef/spelunky-ds#5]
I'm using using this issue more as an opportunity to recount my own experiences related to examining the code of Spelunky Classic, rather than pointing out a specific issue in this project.

Late 2017, I started working and quickly abandoned [my own project](https://github.com/RetroEdit/SpelunkyCommunityUpdateProject) to examine Spelunky Classic's code. Somehow, after almost forgetting about this old project, I stumbled across this port.

Firstly, I just wanted to post here that a C++ version of Spelunky Classic, even if it was done when you were less experienced, is still a useful resource and good starting point for future documentation, and hopefully further modding, of the game.

As for my own experience with code analysis, one particular detail stands out: when I was examining the code for Spelunky Classic, I discovered the level generation pathing loops were suboptimal, and waste many repetitions trying cases that are guaranteed to fail. This was one of the bugs I fixed in my own version of the code, among others; there was also a bug where [dropped ropes did not trigger arrow traps](https://github.com/RetroEdit/SpelunkyCommunityUpdateProject/issues/1), compared to ropes thrown vertically upwards that do trigger arrow traps.

My own code has other issues, though, namely that it currently fails to run due to bad testing practices after a foolish attempt to majorly refactor the tiling code to be "better". I could probably rollback to a previous version, but opening up GameMaker 8.1 (which doesn't appear to have a command line tool!) to compile each time was painful and time-consuming, so I really appreciate knowing a C++ port exists.

Going forward, I think an interesting project that might be worthwhile someday is to port over the mods to C++. Also, I think it would interesting to maintain a version of the code that is annotated with bug fixes found by the Spelunky Community Update Project, myself, and others. I don't know if this project aims to be a perfect port of Spelunky Classic as written by Derek Yu, but I think it would be nice to have at least one "unmodified" (but translated into C++) version of the source around.

----

Oh, and here's another actual bug I discovered in the generation algorithm: [Shop generation biases severely towards shops with right entrances](https://github.com/RetroEdit/SpelunkyCommunityUpdateProject/issues/14). But most of the other issues I added to my repo are apparently dubious, looking back at them.

Oh, my commit notes have some real gold: ["removing generation bias for yeti lairs and alien ships"](https://github.com/RetroEdit/SpelunkyCommunityUpdateProject/commit/632fb044cfafa4952d11404efae6d4e9ad1d95a9). I really forgot how deeply I examined that code and how detailed my notes were.

**Comment by RetroEdit** [comment]
Oh, and here's another actual bug I discovered in the generation algorithm: [Shop generation biases severely towards shops with right entrances](https://github.com/RetroEdit/SpelunkyCommunityUpdateProject/issues/14). But most of the other issues I added to my repo are apparently dubious, looking back at them.

**Comment by dbeef** [comment]
Glad to encounter another Spelunky enthusiast. ;)

There are two things I would like to address: 
- Using original, Game-Maker code for reference when re-creating Spelunky Classic in C++
- Future additions / modding support

When developing I was mostly focused on hardware restrictions imposed on me, and how do I realize certain parts of the project within the framework of libnds and the homebrew NDS toolchain vendored by devkitPro, i.e tile rendering, sprite rendering, playing sounds, reading input, compiling and accessing assets within the game, debugging.
As C++ was still a new thing to me, even language was sometimes a barrier to me (I wish I could have some time to refactor this project right now, but I will come to this matter later in this reply).

Thus, when it came to re-creating certain game mechanics from the original game, I usually fell back to just implement those by heart, as I played the original game a lot and knew how NPC's behave - quite lame, but the final result was satisfying enough. 

When it came to implementing level generator, again I found some point of reference outside the original code in form of some Youtube tutorials.

So, as my code takes only inspiration from the original mechanics, I probably did not copy the bugs it contained (rather introducing my own). I was too lazy to learn Game Maker and analyze original sources.

Coming back to the matter of future additions, refactoring, documenting, modding support, etc.

Lots of things changed since I was majorly commited to development of this project, having acquired a full-time junior CPP dev job, and investing my time into OpenGL, working on [blue](https://github.com/dbeef/blue) renderer.

Because of that, I developed taste for creating a multiplatform project, having OpenGL as a backbone of its renderer and modern CMake as the founding stone for targeting multiple platforms.

As I like developing for old consoles, I done some research on the homebrew PSP development. PSP happens to support very early OpenGL version 1.3, compliant with OpenGL ES 1.0. 
So my idea was to reuse those parts of SpelunkyNDS sources that were platform-independent, and rewire them to use the new renderer I would write in OpenGL. 
Here's where SpelunkyPSP originated:

https://github.com/dbeef/spelunky-psp

It's still in its infancies, having done only level renderer, without actual game, but it provides Linux and PSP builds, and its actually done in a clean way from the beginning.

And finally, why am I saying that - as everyone, I too want to develop myself, and while SpelunkyNDS was a very satisfying project to be developed, I would like to focus on the PSP-version,  as it utilizes more technologies I use at work and in other, personal projects.

It will be easier to maintain (having the potential to build, run and debug on the host platform) and to be modded, and it also has much more potential when it has ancient OpenGL version as its rendering API vendor.
Just look at the list of devices supporting OpenGL ES 1.0:

https://en.wikipedia.org/wiki/OpenGL_ES#OpenGL_ES_1.0_2

I am not saying I abandon Spelunky-NDS, but its definitely not of priority to me. 
You can treat Spelunky-PSP as a second take on porting the game to C++ world.

**Comment by RetroEdit** [comment]
I appreciate your detailed response. I think compatibility is an important aspect when developing such a port, so I appreciate the consideration you've put into making the PSP port more cross-platform friendly.

I would not consider you "lazy" for not digging into the GameMaker source; it was quite a time investment and there are still things I don't understand because GameMaker's documentation is disorganized in certain regards. The scripts for game logic are fairly similar to C++, but all the rendering and package management is handled by the GameMaker executable non-transparently, so understanding how the different parts work together is something I am still not confident in.

I have actually been thinking off-hand about creating my own bug-for-bug game logic port of the original game in C++, so knowing your port is not this ambitious is somewhat reassuring. Once again, this is not an indictment of your project's goals; generally I have pursued more reverse-engineering personal projects than software development projects, so my interests lie in a different direction. My reverse-engineering methodology has grown in sophistication over the past few years, so if I were to come back to this project, I think I would be able to speed up certain aspects on the software development side. I do not plan on doing this in the next few years, so I may not ultimately be the one to accomplish it. I may actually just wait for Derek Yu to release the source to Spelunky HD  so that I could analyze both projects easily in one go-around (releasing the source for Spelunky HD is something I remember Yu saying he would do, though that may have changed as a result of the impending release of Spelunky 2). Perhaps a bit too long-term on my part, as the project may lose relevance to me and others over that timespan, but I will ideally have much more experience by the time I get back to it. Of course, doing projects like these is the way one gains more experience, but there are other projects that have higher priority for me at the moment.

On a more general note, my interest in these projects may be a bit different that most people. I find understanding the thought-process behind game development interesting, so examining the level generation logic was the first thing I did, leading to the discovery of many, usually small, generation biases in the original code. Preserving these mistakes is a goal of mine out of this interest, so that even if a more refined codebase gets built on top of it, documentation of the original game logic in all its glory gets documented somewhere for general interest. It could also be useful for speedrunners of Spelunky Classic, though it is not as popular to speedrun as the more polished HD port.
