### ISSUE TITLE
File Not Running on DSi

### ISSUE THREAD

**Issue by MegaKiwiCoder** [dbeef/spelunky-ds#6]
I got a new DSi recently, and I thought it would be fun to get an R4 cartridge so I could run this and [dslinux](https://www.dslinux.org). But what I found was it would display a blank white screen, and would not fully load the ROM. I decided to get to the bottom of this. I used [NDSFactory](https://github.com/Luca1991/NDSFactory) to extract the contents of the ROM. I put the files on a microSD Card and stuck it into the R4 cartridge and stuck that into my DSi. The game was missing _dsmenu.dat. My question is can _dsmenu.dat be included in the next release?

**Comment by dbeef** [comment]
Hey man, thanks for trying SpelunkyNDS. The information I should have put somewhere - I ran it through TWiLightMenu:

https://github.com/DS-Homebrew/TWiLightMenu

At some point in development I hit a wall, audio would not work at all (I did not diagnose the root cause) and running SpelunkyNDS through TWiLightMenu did fix the problem.

**Comment by MegaKiwiCoder** [comment]
Thanks! I thought TWiLightMenu booted immediately when going to [stylehax](https://www.stylehax.net). I'm new to DS Homebrew stuff.

**Comment by dbeef** [comment]
No problem, glad to help ;)
